apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - dev-namespace.yaml

patches:
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: nginx-html
