apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>NGINX - Environnement DEV</title>
        <style>
            body {
                background-color: #1e90ff;   /* bleu dev */
                color: white;
                font-family: Arial, sans-serif;
                text-align: center;
                padding-top: 100px;
            }
            h1 { font-size: 48px; }
            p { font-size: 22px; }
        </style>
    </head>
    <body>
        <h1>Environnement DEV</h1>
        <p>NGINX tourne ici !</p>
    </body>
    </html>
