apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
  namespace: apache
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Apache - Environnement OK</title>
        <style>
            body {
                background-color: #d62300;
                color: white;
                font-family: Arial, sans-serif;
                text-align: center;
                padding-top: 100px;
            }
            h1 { font-size: 48px; }
            p { font-size: 22px; }
        </style>
    </head>
    <body>
        <h1>ðŸ”¥ Apache fonctionne correctement !</h1>
        <p>Vous Ãªtes sur le service <strong>Apache</strong>.</p>
    </body>
    </html>
