apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: prod
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>NGINX - Environnement PROD</title>
        <style>
            body {
                background-color: #28a745;   /* vert prod */
                color: white;
                font-family: Arial, sans-serif;
                text-align: center;
                padding-top: 100px;
            }
            h1 { font-size: 48px; }
            p { font-size: 22px; }
        </style>
    </head>
    <body>
        <h1>Environnement PROD</h1>
        <p>NGINX fonctionne parfaitement.</p>
    </body>
    </html>
